### ISSUE TITLE
Update to reflex-0.5

### ISSUE THREAD

**Issue by RasmusKlett** [diagrams/diagrams-reflex#6]
Is anyone working on updating this to reflex-0.5 and reflex-dom-0.4? I'm interested in using the library, but am using the newer libraries

**Comment by RasmusKlett** [comment]
I've started the work at https://github.com/RasmusKlett/diagrams-reflex.
It's mostly converting from using String to Text, but my changes might be a little rough, since I don't know my way around neither this library or Diagrams. It compiles with ghcjs 8.0.1 now, but currently there's something wonky with the Reflex events not firing.
Also, I didn't update the examples, tests or stack.yaml at all.

**Comment by byorgey** [comment]
I don't think anyone is working on it that I know of.  Thanks for working on it.  Let us know if you have any questions about the diagrams side of things!

**Comment by RasmusKlett** [comment]
I switched my approach to the task I am solving, so I unfortunately won't be finishing the update.

**Comment by byorgey** [comment]
No worries, thanks for letting us know!  I might have a student work on it this summer since we may want to use it as well.
